
package by.bsuir.aipos.sem6.soap.artifacts;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SoapService", targetNamespace = "http://controller/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "requestToDeleteRecord", targetNamespace = "http://controller/", className = "by.bsuir.aipos.sem6.soap.artifacts.RequestToDeleteRecord")
    @ResponseWrapper(localName = "requestToDeleteRecordResponse", targetNamespace = "http://controller/", className = "by.bsuir.aipos.sem6.soap.artifacts.RequestToDeleteRecordResponse")
    @Action(input = "http://controller/SoapService/requestToDeleteRecordRequest", output = "http://controller/SoapService/requestToDeleteRecordResponse")
    public String requestToDeleteRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "requestToCreateRecord", targetNamespace = "http://controller/", className = "by.bsuir.aipos.sem6.soap.artifacts.RequestToCreateRecord")
    @ResponseWrapper(localName = "requestToCreateRecordResponse", targetNamespace = "http://controller/", className = "by.bsuir.aipos.sem6.soap.artifacts.RequestToCreateRecordResponse")
    @Action(input = "http://controller/SoapService/requestToCreateRecordRequest", output = "http://controller/SoapService/requestToCreateRecordResponse")
    public String requestToCreateRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "requestToRetrieveRecord", targetNamespace = "http://controller/", className = "by.bsuir.aipos.sem6.soap.artifacts.RequestToRetrieveRecord")
    @ResponseWrapper(localName = "requestToRetrieveRecordResponse", targetNamespace = "http://controller/", className = "by.bsuir.aipos.sem6.soap.artifacts.RequestToRetrieveRecordResponse")
    @Action(input = "http://controller/SoapService/requestToRetrieveRecordRequest", output = "http://controller/SoapService/requestToRetrieveRecordResponse")
    public String requestToRetrieveRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "requestToUpdateRecord", targetNamespace = "http://controller/", className = "by.bsuir.aipos.sem6.soap.artifacts.RequestToUpdateRecord")
    @ResponseWrapper(localName = "requestToUpdateRecordResponse", targetNamespace = "http://controller/", className = "by.bsuir.aipos.sem6.soap.artifacts.RequestToUpdateRecordResponse")
    @Action(input = "http://controller/SoapService/requestToUpdateRecordRequest", output = "http://controller/SoapService/requestToUpdateRecordResponse")
    public String requestToUpdateRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
